### ISSUE TITLE
gulp serve: throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by pablorsk** [DanWahlin/AngularIn20TypeScript#13]
Having problems with `gulp serve`. The browser is open, but fail the watcher. This is the logs:

```
$ gulp serve
[15:38:07] Using gulpfile ~/AngularIn20TypeScript/gulpfile.js
[15:38:07] Starting 'compile-ts'...
[15:38:07] Starting 'watch'...
[15:38:07] Finished 'watch' after 12 ms
[15:38:08] Finished 'compile-ts' after 1.17 s
[15:38:08] Starting 'serve'...
Starting browserSync and superstatic...
[15:38:08] Finished 'serve' after 37 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/weinre/web/client ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/pablorsk/AngularIn20TypeScript/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/pablorsk/AngularIn20TypeScript/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/pablorsk/AngularIn20TypeScript/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/pablorsk/AngularIn20TypeScript/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/pablorsk/AngularIn20TypeScript/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/pablorsk/AngularIn20TypeScript/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

The line with `Error: watch` change randomly when I run `gulp serve`. Return lines like:
- `Error: watch node_modules/lodash/fp/thru.js ENOSPC`
- `Error: watch node_modules/weinre/web/target ENOSPC`
- `Error: watch node_modules/weinre/web/doc ENOSPC`

**Comment by DanWahlin** [comment]
Thanks for the pull request on this stuff - appreciate it. There are a few other updates I'd like to do but just don't have to get to them right now unfortunately.

**Comment by pablorsk** [comment]
ouch! That saddens me.

You could leave open the issue if someone else could help me? Who knows... :P

**Comment by DanWahlin** [comment]
Not sure I follow. The pull request seemed to have fixed things for me? You still seeing a problem? Sorry - under some major stress right now on a project so I might have misunderstood what you ran into. Just don't have much time for this right now sadly. But, let me know.

**Comment by pablorsk** [comment]
I'm sorry for my bad English. Exactly, I fix some problems with deprecated things, but I got to this point and I can't continue with this isse. I can't resolve yet this issue.

Maybe someone can help me. 

Thanks for your quickly response.

**Comment by DanWahlin** [comment]
It seems to be loading correctly for me - just tried it multiple times. I'm running the way the readme shows though which is `npm start`.

**Comment by DanWahlin** [comment]
Just tried `gulp serve` and it works OK too. See this now, "fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version." but the browser does load correctly from what I can tell. Going to try it on Windows real quick though.

**Comment by DanWahlin** [comment]
Just updated it quickly to use Typings instead of TSD. Seems to be loading everything correct when running `npm start` or `gulp serve` but let me know if you continue to see problems.

**Comment by pablorsk** [comment]
I try with your last changes, but does not work either. node version maybe? I try on another PC (with Ubuntu too), but the problem don't exist. My PC is the problem.

I have node v4.4.3, the other PC have v5.1.0.

-- EDIT --
I upgrade node to v5.11.0 but the problem persist  :'/

**Comment by DanWahlin** [comment]
Hard to say then if it seems isolated to your one machine. Could be a Node version issue. I'm running 6.0.0 right now. Normally I'd say that's not the issue though as I haven't had a single issue across Node versions since the initial 4.0.0 release. But, it's possible it could be that.

**Comment by pablorsk** [comment]
The problem was kernel parameters -_-. This is the solution:

``` bash
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

Thanks a lot @DanWahlin

**Comment by DanWahlin** [comment]
Glad you figured it out. Wouldn't have guessed that one. :-)

**Comment by tonymj76** [comment]
thanks so much @pablorsk you save me alot of work
